### ISSUE TITLE
How do you do the training and output the SVM file?

### ISSUE THREAD

**Issue by pinglamb** [rhcpfan/ios-rubik-solver#1]
This project is super awesome.

I am learning 1-look PLL (algo + 2-side recognition) (https://sarah.cubing.net/3x3x3/pll-recognition-guide#section/introduction) and would like to use this as reference for building an app to recognize the PLL cases.

How do I train the SVM with my own cube and output as YAML?

Thanks for the awesome work.

**Comment by rhcpfan** [comment]
Hello and thanks for the feedback!

If you're willing to train an SVM to recognise your own cube, you'd need to take pictures of the cube, extract the 3 faces from that picture and get the undistorted images of the 3 faces. You need to do this multiple times, in various lightning conditions until you get enough samples. Based on the obtained images, you need to extract the colour patches of each cubie and feed them to the SVM.

Since I already have the code that does that, I will add it to the project as a new feature in the near future (hopefully this week).

**Comment by pinglamb** [comment]
Thank you so much. Looking forwards to it.

**Comment by pinglamb** [comment]
5d la

**Comment by dzin18** [comment]
@rhcpfan 
how to train my own data ? thanks!

**Comment by rhcpfan** [comment]
I have just added code for training the color detection SVM on device. It works like this:

1. At the first launch of the app, the pre-trained model is used to detect colors;
2. You capture the images of a cube, go to the color correction screen, correct the colors (if needed);
3. After you make the color corrections, the images of the cube faces are saved on the device in the `NSDocuments` directory (accessible via iTunes if you want to see the image files);
4. When you launch the app again, every image in the `NSDocuments` directory matching a naming format (starts with `cubeface_`) is used to train a new SVM (see `SVMTrainer` class). This one is also saved in `NSDocuments` as `svm-trained-on-device.yml`;
5. When you open the app again, if `svm-trained-on-device.yml` is found in `NSDocuments`, it will be used for detection.

Sorry for the long delay 😅
